function net = modify_network(net, num_layers)
%net=load('..\..\data\cifar-lenet\net-trained.mat');
net.layers(num_layers+1:end)=[];
net.layers{num_layers} = struct('type', 'globalpool', ...
'method', 'max') ;
%net.layers{num_layers+1} = struct('type', 'conv', ...
%                           'weights', {{1/64*ones(1,1,64,2, 'single'), zeros(1,2,'single')}}, ...
%                           'learningRate', 0, ...
%                           'stride', 1, ...
%                           'pad', 0) ;